
encrypted_message = 'PD DPDSQSSD OWDYESY QOPEQH-DPDS, DSKGH TESZQSY XEPQPRO PDQSGGPISDTS ZISDTH FP6 ESTEWPQR TZFXEPYIS FZQOSFZQPTR ZGWFDWR ZGZD QWEPDI QC TEZTN DZAP TCYSR, PDTGWYPDI SDPIFZ - KOPTO TEHVQZDZGHRQR OZY QOCWIOQ WDXESZNZXGS. QWEPDIR QSZF, PDTGWYPDI LCZD TGZENS, ZDZGHAS SDPIFZ FSRRZISR KOPGS OS XWPGYR Z FZTOPDS QC YSTPVOSE QOSF. QWEPDI ZDY QSZF UPDZGGH RWTTSSY ZDY XSTCFS OSECSR, XWQ PD DPDSQSSD OWDYESY UPQH-QKC QOS BWPSQ ISDPWR SDTCWDQSER YPRIEZTS KOSD ZWQOCEPQPSR ESMSZG OS PR IZH ZDY RSDY OPF QC VEPRCD'

key = ', .-ETAIONSRHDLUCMFYWGPBVKXQJZ'
alphabet = ', .-SDPZQERTIYWGOFHCXKVNUAMLBJ'
result = ''

for i in range(0,29):
    print(alphabet[i] + ', ' + key[i])

for letter in encrypted_message:
    loc = alphabet.find(letter)
    result += key[loc]

print(result)

# cil, ce, itl, at, wdo, ar, of, etl, cam, oce, ogf, hiy
